[package]
name = "emergency_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio-stream = "0.1"
tokio = {version = "1.25.0", features = ["full"]}